version: '3.9'
services:
  php-env:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./vite-project/dist:/var/www/html
      - ./src:/var/www/html/src
    ports:
      - 9000:80
      - 9443:443
    depends_on:
      - mysql_db
    environment:
      SSL_PASSPHRASE: coldtea
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_ARBITRARY: 1  
    depends_on:
      - mysql_db