version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hacking

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb

  apache2:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./ssl:/etc/ssl
      - ./html:/var/www/html
      - ./config:/etc/apache2/sites-available
    ports:
      - 8443:8443
      - 9443:9443

  express:
    build:
      context: nodejs
      dockerfile: Dockerfile
    volumes:
      - ./ssl:/etc/ssl
    ports:
      - 3000:3000
